concurso/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from vehiculos.views.Vehiculo import VehiculoCreate, VehiculoDelete, VehiculoUpdate, VehiculoDetailView, VehiculoListView
from vehiculos.views.Marca import MarcaCreate, MarcaUpdate, MarcaDelete, MarcaDetailView, MarcaListView
from vehiculos.views.Institucion import InstitucionCreate, InstitucionUpdate, InstitucionDelete, InstitucionDetailView, InstitucionListView
from django.contrib.auth.decorators import login_required
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^inicio$', 'vehiculos.views.Usuarios.inicio', name='inicio'),
    url(r'^$', login_required(VehiculoListView.as_view(), login_url='/inicio'), name='vehiculos_registrados'),
    # vehiculo crud
    url(r'^vehiculos_registrados/$', login_required(VehiculoListView.as_view(), login_url='/inicio'), name='vehiculos_registrados'),
    url(r'^vehiculo/(?P<pk>\d+)/detalles/$', login_required(VehiculoDetailView.as_view(), login_url='/inicio'), name='vehiculo_detalles'),
    url(r'vehiculo/agregar/$', login_required(VehiculoCreate.as_view(), login_url='/inicio'), name='vehiculo_guardar'),
    url(r'vehiculo/(?P<pk>\d+)/$', login_required(VehiculoUpdate.as_view(), login_url='/inicio'), name='vehiculo_modificar'),
    url(r'vehiculo/(?P<pk>\d+)/eliminar/$', login_required(VehiculoDelete.as_view(), login_url='/inicio'), name='vehiculo_eliminar'),
    #marca crud
    url(r'^marcas_registradas/$', login_required(MarcaListView.as_view(), login_url='/inicio'), name='marcas_registradas'),
    url(r'^marca/(?P<pk>\d+)/detalles/$', login_required(MarcaDetailView.as_view(), login_url='/inicio'), name='marca_detalles'),
    url(r'marca/agregar/$', login_required(MarcaCreate.as_view(), login_url='/inicio'), name='marca_guardar'),
    url(r'marca/(?P<pk>\d+)/$', login_required(MarcaUpdate.as_view(), login_url='/inicio'), name='marca_modificar'),
    url(r'marca/(?P<pk>\d+)/eliminar/$', login_required(MarcaDelete.as_view(), login_url='/inicio'), name='marca_eliminar'),
    #institucion crud
    url(r'^instituciones_registradas/$', login_required(InstitucionListView.as_view(), login_url='/inicio'), name='instituciones_registradas'),
    url(r'^institucion/(?P<pk>\d+)/detalles/$', login_required(InstitucionDetailView.as_view(), login_url='/inicio'), name='institucion_detalles'),
    url(r'institucion/agregar/$', login_required(InstitucionCreate.as_view(), login_url='/inicio'), name='institucion_guardar'),
    url(r'institucion/(?P<pk>\d+)/$', login_required(InstitucionUpdate.as_view(), login_url='/inicio'), name='institucion_modificar'),
    url(r'institucion/(?P<pk>\d+)/eliminar/$', login_required(InstitucionDelete.as_view(), login_url='/inicio'), name='institucion_eliminar'),
    #usuario del sistema
    url(r'^cerrar/$', 'vehiculos.views.Usuarios.cerrar_sesion', name="cerrar_sesion"),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT,}
    ),
)

vehiculos/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Marca(models.Model):
    marca = models.CharField(max_length=150, null=False, unique=True)
    fecha_registro = models.DateTimeField(auto_now=True)
    def __unicode__(self):
        return '-'.join([self.marca])

class Institucion(models.Model):
    institucion = models.CharField(max_length=150, null=False, unique=True)
    fecha_registro = models.DateTimeField(auto_now=True)
    def __unicode__(self):
        return '-'.join([self.institucion])

class Vehiculo(models.Model):
    placas = models.CharField(max_length=150, null=False)
    modelo = models.CharField(max_length=150, null=False)
    anyo = models.PositiveIntegerField()
    marca = models.ForeignKey(Marca)
    institucion = models.ForeignKey(Institucion)
    fecha_vencimiento = models.DateField()
    foto = models.ImageField(upload_to='vehiculos')
    fecha_registro = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '-'.join([self.placas, self.modelo])

concurso/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>CONVE | {% block title %}Principal{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/jquery-ui-1.10.3.custom.min.css" rel="stylesheet">
    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <script src="{{ STATIC_URL }}js/jquery-1.10.2.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.js" type="text/javascript"></script>
    {% block extrahead %}
    {% endblock %}
    <script type="text/javascript">
        $(function () {
            $('.dropdown-toggle').dropdown();
            {% block jquery %}

            {% endblock %}
        });
    </script>
</head>

<body>
<div class="container">
    <section id="contenido" class="row">
        {% block contenido %}

        {% endblock %}
    </section>
</div>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="/">CONVE</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="active dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Vehiculos
                            <b class="caret">

                            </b>
                        </a>
                        <ul class="dropdown-menu">
                            {% if perms.vehiculos.add_vehiculo %}
                                <li>
                                    <a href="{% url "vehiculo_guardar" %}">
                                        Registrar
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <a href="{% url "vehiculos_registrados" %}">
                                    Lista de registros
                                </a>
                            </li>

                        </ul>
                    </li>
                    <li class="active dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Institución
                            <b class="caret">

                            </b>
                        </a>
                        <ul class="dropdown-menu">
                            {% if perms.vehiculos.add_institucion %}
                                <li>
                                    <a href="{% url "institucion_guardar" %}">
                                        Registrar
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <a href="{% url "instituciones_registradas" %}">
                                    Lista de registros
                                </a>
                            </li>

                        </ul>
                    </li>
                    <li class="active dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Marca
                            <b class="caret">

                            </b>
                        </a>
                        <ul class="dropdown-menu">
                            {% if perms.vehiculos.add_marca %}
                                <li>
                                    <a href="{% url "marca_guardar" %}">
                                        Registrar
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <a href="{% url "marcas_registradas" %}">
                                    Lista de registros
                                </a>
                            </li>

                        </ul>
                    </li>
                    <li class="dropdown" id="accountmenu">
                        {% if user.is_authenticated %}
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Usuario: {{ user }}
                                    <b class="caret"></b>
                                </a>
                        {% else %}
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Usuario: Anonimo
                                    <b class="caret"></b>
                                </a>
                        {% endif %}

                        <ul class="dropdown-menu">
                            {% if not user.is_authenticated %}
                                <li><a href="{% url "inicio" %}">Login</a></li>
                            {% else %}
                                <li class="divider"></li>
                                <li><a href="{% url "cerrar_sesion" %}">Logout</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>

</body>
</html>

concurso/templates/index.html
{% extends "base.html" %}

{% block contenido %}
    {% load thumbnail %}
    <img src="{{ datos.dato.imagen|thumbnail_url:'avatar' }}" alt=""/>
    {% for dato in vehiculos %}
        <li>
            Placa: {{ dato.placas }}
            <img src="{{ dato.imagen |thumbnail_url:'pequenyo' }}" alt=""/>
        </li>
    {% empty %}
        <li>Aún no hay vehiculos registrados</li>
    {% endfor %}
{% endblock %}

concurso/templates/inicio.html
{% block extrahead %}
    <!-- Le styles -->
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">

    <link href="{{ STATIC_URL }}css/bootstrap-responsive.css" rel="stylesheet">


    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="{{ STATIC_URL }}js/jquery-1.10.2.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-button.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/application.js" type="text/javascript"></script>
{% endblock %}

{% block contenido %}

    <div class="container">
        <h3>Bienvenido a CONVE.</h3>
        <fieldset>
            <legend>Formulario de ingreso</legend>
            <form id='formulario' method='post' action='' class="form-horizontal well form-control">{% csrf_token %}
                    {{formulario.as_p}}
                <p><input type="submit" value="Ingresar" class="btn btn-primary button-loading"/></p>
            </form>
        </fieldset>

    </div>
{% endblock %}

concurso/templates/no_activo.html
{% block contenido %}
    <h1>El usuario no esta activo</h1>
    <br />
    <ul>
		<li><a href="/inicio">Iniciar sesión</a></li>
	</ul>
{% endblock %}

concurso/templates/no_usuario.html
{% block contenido %}
    <p>El usuario y la contraseña no coinciden o no existen </p>
    <br />
    <ul>
		<li><a href="/inicio">Iniciar sesión</a></li>
	</ul>
{% endblock %}

concurso/templates/nuevo_usuario.html
{% extends 'base.html' %}
{% block titulo %}
    Nuevo usuario
{% endblock %}
{% block encabezado %}
    <h1>Registrar nuevo usuario</h1>
{% endblock %}
{% block contenido %}
    <form id="formulario" method="post" action="">{% csrf_token %}
    	<table>{{formulario}}</table>
    	<p><input type="submit" value="Registrar" /></p>
    </form>
{% endblock %}