concurso/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from vehiculos.views.Vehiculo import VehiculoCreate, VehiculoDelete, VehiculoUpdate, VehiculoDetailView, VehiculoListView
from vehiculos.views.Marca import MarcaCreate, MarcaUpdate, MarcaDelete, MarcaDetailView, MarcaListView
from vehiculos.views.Institucion import InstitucionCreate, InstitucionUpdate, InstitucionDelete, InstitucionDetailView, InstitucionListView
from django.contrib.auth.decorators import login_required
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^inicio$', 'vehiculos.views.Usuarios.inicio', name='inicio'),
    url(r'^$', login_required(VehiculoListView.as_view(), login_url='/inicio'), name='vehiculos_registrados'),
    # vehiculo crud
    url(r'^vehiculos_registrados/$', login_required(VehiculoListView.as_view(), login_url='/inicio'), name='vehiculos_registrados'),
    url(r'^vehiculo/(?P<pk>\d+)/detalles/$', login_required(VehiculoDetailView.as_view(), login_url='/inicio'), name='vehiculo_detalles'),
    url(r'vehiculo/agregar/$', login_required(VehiculoCreate.as_view(), login_url='/inicio'), name='vehiculo_guardar'),
    url(r'vehiculo/(?P<pk>\d+)/$', login_required(VehiculoUpdate.as_view(), login_url='/inicio'), name='vehiculo_modificar'),
    url(r'vehiculo/(?P<pk>\d+)/eliminar/$', login_required(VehiculoDelete.as_view(), login_url='/inicio'), name='vehiculo_eliminar'),
    #marca crud
    url(r'^marcas_registradas/$', login_required(MarcaListView.as_view(), login_url='/inicio'), name='marcas_registradas'),
    url(r'^marca/(?P<pk>\d+)/detalles/$', login_required(MarcaDetailView.as_view(), login_url='/inicio'), name='marca_detalles'),
    url(r'marca/agregar/$', login_required(MarcaCreate.as_view(), login_url='/inicio'), name='marca_guardar'),
    url(r'marca/(?P<pk>\d+)/$', login_required(MarcaUpdate.as_view(), login_url='/inicio'), name='marca_modificar'),
    url(r'marca/(?P<pk>\d+)/eliminar/$', login_required(MarcaDelete.as_view(), login_url='/inicio'), name='marca_eliminar'),
    #institucion crud
    url(r'^instituciones_registradas/$', login_required(InstitucionListView.as_view(), login_url='/inicio'), name='instituciones_registradas'),
    url(r'^institucion/(?P<pk>\d+)/detalles/$', login_required(InstitucionDetailView.as_view(), login_url='/inicio'), name='institucion_detalles'),
    url(r'institucion/agregar/$', login_required(InstitucionCreate.as_view(), login_url='/inicio'), name='institucion_guardar'),
    url(r'institucion/(?P<pk>\d+)/$', login_required(InstitucionUpdate.as_view(), login_url='/inicio'), name='institucion_modificar'),
    url(r'institucion/(?P<pk>\d+)/eliminar/$', login_required(InstitucionDelete.as_view(), login_url='/inicio'), name='institucion_eliminar'),
    #usuario del sistema
    url(r'^cerrar/$', 'vehiculos.views.Usuarios.cerrar_sesion', name="cerrar_sesion"),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT,}
    ),
)

vehiculos/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from vehiculos.views.Vehiculo import VehiculoCreate, VehiculoDelete, VehiculoUpdate, VehiculoDetailView, VehiculoListView
from vehiculos.views.Marca import MarcaCreate, MarcaUpdate, MarcaDelete, MarcaDetailView, MarcaListView
from vehiculos.views.Institucion import InstitucionCreate, InstitucionUpdate, InstitucionDelete, InstitucionDetailView, InstitucionListView
from django.contrib.auth.decorators import login_required
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

login_url='/inicio'

urlpatterns = patterns('',
    url(r'^inicio$', 'vehiculos.views.Usuarios.inicio', name='inicio'),
    url(r'^$', login_required(VehiculoListView.as_view(), login_url='/inicio'), name='vehiculos_registrados'),
    # vehiculo crud
    url(r'^vehiculos_registrados/$', login_required(VehiculoListView.as_view(), login_url), name='vehiculos_registrados'),
    url(r'^vehiculo/(?P<pk>\d+)/detalles/$', login_required(VehiculoDetailView.as_view(), login_url), name='vehiculo_detalles'),
    url(r'vehiculo/agregar/$', login_required(VehiculoCreate.as_view(), login_url), name='vehiculo_guardar'),
    url(r'vehiculo/(?P<pk>\d+)/$', login_required(VehiculoUpdate.as_view(), login_url), name='vehiculo_modificar'),
    url(r'vehiculo/(?P<pk>\d+)/eliminar/$', login_required(VehiculoDelete.as_view(), login_url), name='vehiculo_eliminar'),
    #marca crud
    url(r'^marcas_registradas/$', login_required(MarcaListView.as_view(), login_url), name='marcas_registradas'),
    url(r'^marca/(?P<pk>\d+)/detalles/$', login_required(MarcaDetailView.as_view(), login_url), name='marca_detalles'),
    url(r'marca/agregar/$', login_required(MarcaCreate.as_view(), login_url), name='marca_guardar'),
    url(r'marca/(?P<pk>\d+)/$', login_required(MarcaUpdate.as_view(), login_url), name='marca_modificar'),
    url(r'marca/(?P<pk>\d+)/eliminar/$', login_required(MarcaDelete.as_view(), login_url), name='marca_eliminar'),
    #institucion crud
    url(r'^instituciones_registradas/$', login_required(InstitucionListView.as_view(), login_url), name='instituciones_registradas'),
    url(r'^institucion/(?P<pk>\d+)/detalles/$', login_required(InstitucionDetailView.as_view(), login_url), name='institucion_detalles'),
    url(r'institucion/agregar/$', login_required(InstitucionCreate.as_view(), login_url), name='institucion_guardar'),
    url(r'institucion/(?P<pk>\d+)/$', login_required(InstitucionUpdate.as_view(), login_url), name='institucion_modificar'),
    url(r'institucion/(?P<pk>\d+)/eliminar/$', login_required(InstitucionDelete.as_view(), login_url), name='institucion_eliminar'),
    #usuario del sistema
    url(r'^cerrar/$', 'vehiculos.views.Usuarios.cerrar_sesion', name="cerrar_sesion"),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT,}
    ),
)

vehiculos/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Marca(models.Model):
    marca = models.CharField(max_length=150, null=False, unique=True)
    fecha_registro = models.DateTimeField(auto_now=True)
    def __unicode__(self):
        return '-'.join([self.marca])

class Institucion(models.Model):
    institucion = models.CharField(max_length=150, null=False, unique=True)
    fecha_registro = models.DateTimeField(auto_now=True)
    def __unicode__(self):
        return '-'.join([self.institucion])

class Vehiculo(models.Model):
    placas = models.CharField(max_length=150, null=False)
    modelo = models.CharField(max_length=150, null=False)
    anyo = models.PositiveIntegerField()
    marca = models.ForeignKey(Marca)
    institucion = models.ForeignKey(Institucion)
    fecha_vencimiento = models.DateField()
    foto = models.ImageField(upload_to='vehiculos')
    fecha_registro = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '-'.join([self.placas, self.modelo])

vehiculos/views/Institucion.py
from vehiculos.models import Institucion
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView, ListView
from django.core.urlresolvers import reverse_lazy
from django.utils import timezone


class InstitucionDetailView(DetailView):

    queryset = Institucion.objects.all()

    def get_object(self):
        # Call the superclass
        object = super(InstitucionDetailView, self).get_object()
        # Record the last accessed date
        object.last_accessed = timezone.now()
        object.save()
        # Return the object
        return object

class InstitucionCreate(CreateView):
    model = Institucion
    success_url = reverse_lazy('instituciones_registradas')

class InstitucionUpdate(UpdateView):
    model = Institucion
    success_url = reverse_lazy('instituciones_registradas')

class InstitucionDelete(DeleteView):
    model = Institucion
    success_url = reverse_lazy('instituciones_registradas')

class InstitucionListView(ListView):
    model = Institucion
    template_name = 'institucion_list.html'
    paginate_by = 10

vehiculos/views/Marca.py
from vehiculos.models import Marca
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView, ListView
from django.core.urlresolvers import reverse_lazy
from django.utils import timezone


class MarcaDetailView(DetailView):

    queryset = Marca.objects.all()

    def get_object(self):
        # Call the superclass
        object = super(MarcaDetailView, self).get_object()
        # Record the last accessed date
        object.last_accessed = timezone.now()
        object.save()
        # Return the object
        return object

class MarcaCreate(CreateView):
    model = Marca
    success_url = reverse_lazy('marcas_registradas')

class MarcaUpdate(UpdateView):
    model = Marca
    success_url = reverse_lazy('marcas_registradas')

class MarcaDelete(DeleteView):
    model = Marca
    success_url = reverse_lazy('marcas_registradas')

class MarcaListView(ListView):
    model = Marca
    template_name = 'marca_list.html'
    paginate_by = 10  #and that's it !!

vehiculos/views/Usuarios.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required

def inicio(request):
    if not request.user.is_anonymous():
        return HttpResponseRedirect('/')
    if request.method=='POST':
        form = AuthenticationForm(request.POST)
        if form.is_valid:
            usuario = request.POST['username']
            clave = request.POST['password']
            access = authenticate(username=usuario, password=clave)
            if access is not None:
                if access.is_active:
                    login(request, access)
                    #request.session['usuario'] = usuario
                    return HttpResponseRedirect('/')
                else:
                    return render_to_response('no_activo.html', context_instance=RequestContext(request))
            else:
                return render_to_response('no_usuario.html', context_instance=RequestContext(request))
    else:
        form = AuthenticationForm()
    return render_to_response('inicio.html', {'formulario': form}, context_instance=RequestContext(request))


@login_required(login_url='/inicio')
def privado(request):
    usuario = request.user
    return render_to_response('index.html', {'usuario': usuario}, context_instance=RequestContext(request))

@login_required(login_url='/inicio')
def cerrar_sesion(request):
    logout(request)
    #if request.session.has_key('usuario'):
    #    del request.session['usuario']
    return HttpResponseRedirect('/inicio')

vehiculos/views/Vehiculo.py
from vehiculos.models import Vehiculo
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView, ListView
from django.core.urlresolvers import reverse_lazy
from django.utils import timezone


class VehiculoDetailView(DetailView):

    queryset = Vehiculo.objects.all()

    def get_object(self):
        # Call the superclass
        object = super(VehiculoDetailView, self).get_object()
        # Record the last accessed date
        object.last_accessed = timezone.now()
        object.save()
        # Return the object
        return object

class VehiculoCreate(CreateView):
    model = Vehiculo
    success_url = reverse_lazy('vehiculos_registrados')

class VehiculoUpdate(UpdateView):
    model = Vehiculo
    success_url = reverse_lazy('vehiculos_registrados')

class VehiculoDelete(DeleteView):
    model = Vehiculo
    success_url = reverse_lazy('vehiculos_registrados')

class VehiculoListView(ListView):
    model = Vehiculo      # shorthand for setting queryset = models.Car.objects.all()
    template_name = 'vehiculo_list.html'  # optional (the default is app_name/modelNameInLowerCase_list.html; which will look into your templates folder for that path and file)
    paginate_by = 10  #and that's it !!

concurso/templates/vehiculos/institucion_confirm_delete.html
{% extends "base.html" %}

{% block contenido %}
    <form action="" method="post">{% csrf_token %}
        <fieldset>
            <legend>Eliminar Institución</legend>
            <p>
                Estas seguro que deseas eliminar a "{{ object }}"?
            </p>
            <input type="submit" value="Confirmar" class="btn btn-danger"/>
        </fieldset>
    </form>
{% endblock %}

concurso/templates/vehiculos/institucion_detail.html
{% extends "base.html" %}

{% block contenido %}
    <ul>
        <p>
            <li>Marca: {{ object.institucion }}</li>
        </p>
        <p>
            <li>Fecha de registro: {{ object.fecha_registro }}</li>
        </p>
    </ul>
    <ul>
        {% if perms.vehiculos.change_institucion %}
            <a href='{% url "institucion_modificar" object.id %}' class="btn">Modificar</a>
        {% endif %}
        {% if perms.vehiculos.delete_institucion %}
            <a href='{% url "institucion_eliminar" object.id %}' class="btn">Eliminar</a>
        {% endif %}
    </ul>
{% endblock %}

concurso/templates/vehiculos/institucion_form.html
{% extends "base.html" %}


{% block contenido %}
    <form action="" method="post">{% csrf_token %}
        <fieldset>
            <legend>Registrar Institución</legend>
            {{ form.as_p }}

            <input type="submit" value="Guardar" class="btn btn-primary"/>
        </fieldset>
    </form>
{% endblock %}

concurso/templates/vehiculos/institucion_list.html
{% extends "base.html" %}

{% block contenido %}
    <blockquote>
      <p>Lista de instituciones registradas.</p>
    </blockquote>
    <ul>
        {% for dato in object_list %}
            <table class="table table-striped table-hover">
            <tr>
                <td>
                    Institución: {{ dato.institucion }}
                </td>
                <td>
                    <a href='{% url "institucion_detalles" dato.id %}' class="btn">
                        Detalles
                    </a>
                </td>
            </tr>
            </table>
        {% empty %}
            <li>
                Aún no hay instituciones registradas
            </li>
        {% endfor %}
    </ul>

{% endblock %}

concurso/templates/vehiculos/marca_confirm_delete.html
{% extends "base.html" %}

{% block contenido %}
    <form action="" method="post">{% csrf_token %}
        <fieldset>
            <legend>Eliminar Marca</legend>
            <p>
                Estas seguro que deseas eliminar a "{{ object }}"?
            </p>
            <input type="submit" value="Confirmar" class="btn btn-danger"/>
        </fieldset>
    </form>
{% endblock %}

concurso/templates/vehiculos/marca_detail.html
{% extends "base.html" %}

{% block contenido %}
    <ul>
        <p>
            <li>Marca: {{ object.marca }}</li>
        </p>
        <p>
        <li>Fecha de registro: {{ object.fecha_registro }}</li>
        </p>
    </ul>
    <ul>
        {% if perms.vehiculos.change_marca %}
            <a href='{% url "marca_modificar" object.id %}' class="btn">Modificar</a>
        {% endif %}
        {% if perms.vehiculos.delete_marca %}
            <a href='{% url "marca_eliminar" object.id %}' class="btn">Eliminar</a>
        {% endif %}
    </ul>
{% endblock %}

concurso/templates/vehiculos/marca_form.html
{% extends "base.html" %}


{% block contenido %}
    <form action="" method="post">{% csrf_token %}
        <fieldset>
            <legend>Registrar Marca</legend>
            {{ form.as_p }}

            <input type="submit" value="Guardar" class="btn btn-primary"/>
        </fieldset>
    </form>
{% endblock %}

concurso/templates/vehiculos/marca_list.html
{% extends "base.html" %}

{% block contenido %}
    <blockquote>
      <p>Lista de marcas registradas.</p>
    </blockquote>
    <ul>
        {% for dato in object_list %}
            <table class="table table-striped table-hover">
            <tr>
                <td>
                    Marca: {{ dato.marca }}
                </td>
                <td>
                    <a href='{% url "marca_detalles" dato.id %}' class="btn">
                        Detalles
                    </a>
                </td>
            </tr>
            </table>
        {% empty %}
            <li>
                Aún no hay marcas registradas
            </li>
        {% endfor %}
    </ul>

{% endblock %}

concurso/templates/vehiculos/vehiculo_confirm_delete.html
{% extends "base.html" %}

{% block contenido %}
    <form action="" method="post">{% csrf_token %}
        <fieldset>
            <legend>Eliminar Vehiculo</legend>
            <p>
                Estas seguro que deseas eliminar a "{{ object }}"?
            </p>
            <input type="submit" value="Confirmar" class="btn btn-danger"/>
        </fieldset>
    </form>
{% endblock %}

concurso/templates/vehiculos/vehiculo_detail.html
{% extends "base.html" %}

{% block contenido %}
    <ul>
        <h1>
            <li>Placa: {{ object.placas }}</li>
        </h1>
        <p>
            <li>Modelo: {{ object.modelo }}</li>
        </p>
        <p>
            <li>Año: {{ object.anyo }}</li>
        </p>
        <p>
            <li>Marca: {{ object.marca }}</li>
        </p>
        <p>
            <li>Institución: {{ object.institucion }}</li>
        </p>
        <p>
        <li>Fecha de vencimiento: {{ object.fecha_vencimiento }}</li>
        </p>
        {% load thumbnail %}
        <td><img src="{{ object.imagen |thumbnail_url:'grande' }}" alt="" class="img-rounded"/></td>
    </ul>
    <ul>
        {% if perms.vehiculos.change_vehiculo %}
            <a href='{% url "vehiculo_modificar" object.id %}' class="btn">Modificar</a>
        {% endif %}
        {% if perms.vehiculos.delete_vehiculo %}
            <a href='{% url "vehiculo_eliminar" object.id %}' class="btn">Eliminar</a>
        {% endif %}
    </ul>
{% endblock %}

concurso/templates/vehiculos/vehiculo_form.html
{% extends "base.html" %}

{% block jquery %}
    $( "#id_fecha_vencimiento").datepicker({
    inline: true,
    dateFormat: "yy-mm-dd"
    });
{% endblock %}

{% block contenido %}
    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        <fieldset>
            <legend>Registrar Vehiculo</legend>
            {{ form.as_p }}

            <input type="submit" value="Guardar" class="btn btn-primary"/>
        </fieldset>
    </form>
{% endblock %}

concurso/templates/vehiculos/vehiculo_list.html
{% extends "base.html" %}

{% block contenido %}
    <blockquote>
      <p>Lista de vehiculos registrados.</p>
    </blockquote>
    {% load thumbnail %}
    <ul>
        {% for dato in object_list %}
            <table class="table table-striped table-hover">
            <tr>
                <td>
                    Placa: {{ dato.placas }}
                </td>
                <td>
                    Marca: {{ dato.marca }}
                </td>
                <td>
                    <img src="{{ dato.imagen |thumbnail_url:'pequenyo' }}" alt="" class="img-rounded"/>
                </td>
                <td>
                    <a href='{% url "vehiculo_detalles" dato.id %}' class="btn">Detalles</a>
                </td>
            </tr>
            </table>
        {% empty %}
            <li>
                Aún no hay vehiculos registrados
            </li>
        {% endfor %}
    </ul>

{% endblock %}